### ISSUE TITLE
web页面中“configurations”页参数空白错误

### ISSUE THREAD

**Issue by sunnyseaman** [MatteoRagni/AmuleWebUI-Reloaded#16]
web页面中“configurations”页参数空白，表明没有获取到 amule.conf 中的设置参数。
修改了 $HOME/share/amule/webserver/AmuleWebUI-Reloaded/amuleweb-main-prefs.php 文件，在：

	</head>
	<body>  
	
处，改为

	</head>
	<body onLoad="init_data()">
	
成功。

**Comment by MatteoRagni** [comment]
Please use english only.

**Comment by garret** [comment]
I am experiencing exactly the same issue. I tried to look for this `</head><body onLoad="init_data()">` section in the code but could not find it. I guess because the code has been updated since the issue was started. 

Could you help me in understanding how to fix the issue? 
The configuration page works fine when using the default amuleweb template. I also tried with aMule 2.3.1, 2.3.2 and latest svn revision but always get this blank fields in the configuration page.
